# Generated by Django 4.1.5 on 2023-01-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=15, null=True, verbose_name='номенклатура')),
                ('ean', models.IntegerField(verbose_name='EAN/Штрихкод')),
                ('title', models.CharField(max_length=200, verbose_name='наименование товара')),
                ('country', models.CharField(choices=[('VIETNAM', 'Вьетнам'), ('CHINA', 'Китай'), ('MALAYSIA', 'Малайзия'), ('MYANMAR', 'Мьянма'), ('SLOVAKIA', 'Словакия'), ('TAIWAN', 'Тайвань'), ('THAILAND', 'Таиланд'), ('PHILIPPINES', 'Филиппины'), ('JAPAN', 'Япония')], default='VIETNAM', max_length=30, verbose_name='страна производства')),
                ('category', models.CharField(choices=[('ACOUSTICS', 'акустика'), ('ADAPTER', 'адаптер'), ('AUDIO SYSTEM', 'аудиосистема'), ('BATTERY', 'аккумулятор'), ('BT HEADPHONES', 'BT наушники'), ('BT SPEAKER', 'BT колонка'), ('CABLE', 'кабель'), ('CAMERA ACCESSORIES', 'аксессуары для камеры'), ('CARD READER', 'картридер'), ('CASE', 'чехол'), ('CHARGER', 'зарядное устройство'), ('CONSOLE', 'консоль'), ('EXTERNAL SSD', 'внешний SSD'), ('FASTENING', 'крепление'), ('HDMI', 'HDMI'), ('HEADPHONES', 'наушники'), ('HEADPHONES', 'радионаушники'), ('LENS CAP', 'крышка объектива'), ('LIGHT FILTER', 'светофильтр'), ('MEMORY CARD', 'карта памяти'), ('MICROPHONE', 'микрофон'), ('OPTICAL CARE', 'уход за оптикой'), ('PLAYER', 'плеер'), ('POWERBANK', 'ПЗУ'), ('PROTECTIVE FILM', 'защитная пленка'), ('PROTECTIVE GLASS', 'защитное стекло'), ('PS', 'PS'), ('PS ACCESSORIES', 'аксессуары PS'), ('PS GAME', 'игра PS'), ('RECEIVER', 'ресивер'), ('SMARTPHONE', 'смартфон'), ('SMARTPHONE ACCESSORIES', 'аксессуары для смартфона'), ('SONY CAMERA', 'камера Sony'), ('SONY LENS', 'объектив Sony'), ('SOUNDBAR', 'саундбар'), ('SUBWOOFER', 'савбуфер'), ('TAMRON LENS', 'объектив Tamron'), ('TRIPOD', 'штатив'), ('TURNTABLE', 'проигрыватель'), ('TV', 'телевизор'), ('TV ACCESSORIES', 'аксессуары для ТВ'), ('VOICE RECORDER', 'диктофон')], max_length=30, verbose_name='категория товара')),
                ('old_price', models.FloatField(blank=True, null=True, verbose_name='старая цена')),
                ('price', models.FloatField(verbose_name='цена товара')),
                ('is_red_price', models.BooleanField(choices=[(True, 'Красная цена'), (False, 'Черная цена')], verbose_name='Цвет ценника')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'price',
                'ordering': ['ean'],
            },
        ),
    ]
