# Generated by Django 4.1.5 on 2023-02-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(blank=True, choices=[(1, 'АКЦИЯ !!!'), (2, 'Уценка'), (3, 'Витринный образец'), (4, 'Последний экземпляр')], max_length=100, null=True, verbose_name='причина скидки'),
        ),
    ]
