# Generated by Django 4.1.5 on 2023-02-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tags', '0003_alter_product_category_alter_product_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('Акция !!!', 'Акция !!!'), ('Уценка', 'Уценка'), ('Витринный образец', 'Витринный образец'), ('Последний экземпляр', 'Последний экземпляр')], max_length=100, null=True, verbose_name='причина скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_red_price',
            field=models.BooleanField(verbose_name='Цвет ценника'),
        ),
    ]
