# Generated by Django 4.1.5 on 2023-02-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tags', '0004_alter_product_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_red_price',
            field=models.BooleanField(verbose_name='Красный ценник'),
        ),
    ]
