# Generated by Django 4.1.5 on 2023-02-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tags', '0006_alter_product_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.IntegerField(unique=True, verbose_name='EAN/Штрихкод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='номенклатура'),
        ),
    ]
