# Generated by Django 4.1.5 on 2023-04-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tags', '0008_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='наушники', max_length=20, verbose_name='категория товара')),
            ],
            options={
                'verbose_name': 'категория товара',
                'verbose_name_plural': 'категории товаров',
                'db_table': 'category',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BT колонка', 'BT колонка'), ('BT наушники', 'BT наушники'), ('HDMI', 'HDMI'), ('PS', 'PS'), ('ресивер', 'ресивер'), ('адаптер', 'адаптер'), ('автомагнитола', 'автомагнитола'), ('аккумулятор', 'аккумулятор'), ('аксессуары PS', 'аксессуары PS'), ('аксессуары для камеры', 'аксессуары для камеры'), ('аксессуары для смартфона', 'аксессуары для смартфона'), ('аксессуары для ТВ', 'аксессуары для ТВ'), ('акустика', 'акустика'), ('аудиосистема', 'аудиосистема'), ('внешний SSD', 'внешний SSD'), ('диктофон', 'диктофон'), ('зарядное устройство', 'зарядное устройство'), ('защитная пленка', 'защитная пленка'), ('защитное стекло', 'защитное стекло'), ('игра PS', 'игра PS'), ('кабель', 'кабель'), ('камера Sony', 'камера Sony'), ('карта памяти', 'карта памяти'), ('картридер', 'картридер'), ('консоль', 'консоль'), ('крепление', 'крепление'), ('крышка объектива', 'крышка объектива'), ('микрофон', 'микрофон'), ('наушники', 'наушники'), ('объектив Sony', 'объектив Sony'), ('объектив Tamron', 'объектив Tamron'), ('ПЗУ', 'ПЗУ'), ('плеер', 'плеер'), ('проигрыватель', 'проигрыватель'), ('радионаушники', 'радионаушники'), ('ресивер', 'смартфон'), ('сабвуфер', 'сабвуфер'), ('саундбар', 'саундбар'), ('светофильтр', 'светофильтр'), ('телевизор', 'телевизор'), ('уход за оптикой', 'уход за оптикой'), ('чехол', 'чехол'), ('штатив', 'штатив')], help_text='наушники', max_length=30, verbose_name='категория товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('Вьетнам', 'Вьетнам'), ('Китай', 'Китай'), ('Малайзия', 'Малайзия'), ('Мьянма', 'Мьянма'), ('Словакия', 'Словакия'), ('Тайвань', 'Тайвань'), ('Таиланд', 'Таиланд'), ('Филиппины', 'Филиппины'), ('Япония', 'Япония')], default='Вьетнам', help_text='Китай', max_length=30, verbose_name='страна производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.IntegerField(help_text='4548736081680', unique=True, verbose_name='EAN/Штрихкод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='IERM7.WW2', max_length=15, null=True, unique=True, verbose_name='номенклатура(sku/sap)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='IER-M7', max_length=200, verbose_name='наименование товара'),
        ),
    ]
