# Generated by Django 4.1.5 on 2023-04-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tags', '0009_category_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='наушники', max_length=30, verbose_name='категория товара'),
        ),
    ]
