# Generated by Django 4.1.5 on 2023-04-23 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tags', '0012_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(help_text='Китай', on_delete=django.db.models.deletion.CASCADE, to='app_tags.country', verbose_name='страна производства'),
        ),
    ]
